export const metadata = {
  title: "ISLA FOODS",
  description: "Generated by Next.js",
  icons: {
    icon: "/vector.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
